### ISSUE TITLE
Wrong Content-Type with a typical browser Accept header

### ISSUE THREAD

**Issue by cdevienne** [plone/guillotina#203]
With the following 'Accept' request header :

  `Accept: text/html,*/*`

The response Content-Type is "text/html". It think its wrong, it should be application/json:
- The actual content remains application/json, it is not transformed to valid html
- `*/*` clearly allow the server to return something else than text/html
- Even if application/json is not in Accept (and maybe in the absence of text/javascript), the returned content-type should still be application/json, unless of course the content can be rendered as one of the accepted content types.

**Comment by vangheem** [comment]
At least right now, the design of our content negotiation handling is that you register renderers for various content types.

The ones we provide OOTB are:
 - application/json
 - text/html
 - text/plain

Services simple return a data structure and the renderer then decides how to display it.

So, rather than forcing an `application/json` response, I think what is more appropriate here is to wrap the response body in `<html><body>` tags. If the client asks for html, we should give them html. And if a client what json, it should ask for it or if it doesn't care, provide `*/*` and guess the best response.

**Comment by vangheem** [comment]
See https://github.com/plone/guillotina/pull/204

**Comment by cdevienne** [comment]
Hitting the API with a browser is mainly for debugging purpose, and modern browsers will display application/json content with an appropriate interface (hightlighted and with a foldable tree).

It is what I was expecting and led me to create this issue.

Currently, using the browser debugger workaround the 'problem' (it still can display the json as such), but by wrapping the json in a `<html><body>`, it would not work anymore.

So I think the most useful solution is to remove the text/html and text/plain views.

**Comment by cdevienne** [comment]
@vangheem I really fail to see how wrapping json in a html body can be of any interest.

Unless this wrapping does some coloring/formatting, which the browser does well already when receiving application/json content, I strongly suggest to remove the default html view.

Meanwhile, is there any way to disable it ?
