### ISSUE TITLE
Subscriber that needs to access obj.parent and children

### ISSUE THREAD

**Issue by masipcat** [plone/guillotina#418]
Hi,

I'm using a custom subscriber to trigger the indexation of obj Alpha when obj Charlie is modified (the tree looks like A/B/C). The reason to do that is that I'm denormalizing object Charlie into Alpha, so when the object Charlie changes I want to reindex the object Alpha.

```python
@configure.subscriber(for_=(ICharlie, IObjectAddedEvent))
@configure.subscriber(for_=(ICharlie, IObjectModifiedEvent))
async def reindex_parent(obj, event):
    parent = obj.__parent__
    while not IA.providedBy(parent):
        parent = parent.__parent__
    await index_object(parent)
```

And object Alpha has a custom `index_accessor` that looks like this:

```python
@index_field.with_accessor(IAlpha, "children", field_mapping={...})
async def get_children(ob) -> List[Dict]:
    children = []
    async for bravo in ob.async_values():
        async for charlie in bravo.async_values():
            children += [charlie.to_dict()]
    return children
```

The problem is that the notification `ObjectAddedEvent`/`ObjectModifiedEvent` is sent before `request.commit()` is called and this produces `bravo.async_values()` return `[]`.

As a workaround to solve this problem I changed the code into this:

```python
@configure.subscriber(for_=(IProductoOpcion, IObjectAddedEvent))
@configure.subscriber(for_=(IProductoOpcion, IObjectModifiedEvent))
async def reindex_parent(obj, event):
    after_commit(partial(_reindex_parent, obj, event))


async def _reindex_parent(obj, event):
    # ...
    await index_object(parent)
```

But I'd like to know your opinion on this and if there is a better way to do it.

Thank you in advance!

**Comment by vangheem** [comment]
I personally like `after_commit` approach the most. (or better yet, `after_request`?)

You can also look at the current transaction for any objects that have been added to that container with something like this:

```
from guillotina.transactions import get_transaction
txn = get_transaction()
items = [i for i in txn.added.values() if i.uuid == parent.uuid]
```

Another option is to store the newly modified value on the request object and then in your accessor, check to see if you have anything there.

Does that help?

**Comment by masipcat** [comment]
Yes! thank you :-) I'll change the `after_commit` with `after_request`, sounds safer... 

I don't know if would make sense to add a new event `ObjectCommitedEvent` / `ObjectStoredEvent` or maybe fire the notification `ObjectAddedEvent` after the request is committed.

Without checking the code, I understood `BeforeObjectAddedEvent` as "someone is creating a new object, but still not in the tree" and `ObjectAddedEvent` as "a new object was added in the tree". But maybe my interpretation is completely wrong... :P

**Comment by vangheem** [comment]
- ObjectCommitedEvent / ObjectStoredEvent: maybe; however, I'm not necessarily a fan of adding overhead during this phase of the request. Also, txn is closed at this point so any code that interacted with it would need to manage itself and open new txn anyways...
- BeforeObjectAddedEvent: to allow you to dive out/raise an issue before it gets registered on the txn
- ObjectAddedEvent: "added in the tree" -- sort of. The `__parent__` pointer is assigned and txn registers the object; however, it's not committed and any subsequent calls with parent are still doing lookups against the db directly.

Unfortunately, we choose this approach with the ORM because it's faster; however, it does require user to do more work to interact with stuff related to parent/children.

The ORM is more like django or a sql in this way. Not like zodb which hides everything from you.

**Comment by masipcat** [comment]
Ok, good to know :) Thank you!
