### ISSUE TITLE
API versioning 

### ISSUE THREAD

**Issue by AkshJain99** [plone/guillotina#441]
API versioning: Provide a mechanism to version API endpoints. For example, prefixing all urls with /v1, /v2 etc.

**Comment by AkshJain99** [comment]
we can do URI versioning, 
custom request header we can do api verisioning

**Comment by khssnv** [comment]
@AkshJain99, could you give an example on how to do it, please?

**Comment by vangheem** [comment]
@khssnv we kind of decided that in practice, it doesn't make sense for the frame to provide an opinion on how to do this since there are so many different ways to implement API versioning/changes.

I think a simple solution would be to do some combination of deploying differently configured guillotina services published on different urls utilizing a proxy service to publish the different versions at different urls.
