### ISSUE TITLE
Leaf node in the trash bin can loaded by get_object_by_oid

### ISSUE THREAD

**Issue by panjunyong** [plone/guillotina#498]
Even if a tree was moved to trash bin, it seems the leaf node can be still loaded by get_object_by_oid.

This PR only checks the root node of the deleted tree:

https://github.com/plone/guillotina/pull/474/files#diff-e737110ac4b0f4f6ae4a7c6eadbc36c4R183

**Comment by vangheem** [comment]
Right, it checks if any parent is in trash and returns None if it is. So for any leaf node that is trashed or has a parent object that is trashed, it will return None.

**Comment by vangheem** [comment]
Can you write a test case where it behaves in a way you aren't expecting? This should be working correctly.

**Comment by nnnewb** [comment]
Hi, i wrote an simple test to explain this. 

There is two object, a folder, and an child item. when I delete the folder I say the whole tree was moved into trash bin, so if I can't get folder by api like `get_object_by_oid`, I should can't get the child item by the same way.

```text
+---------------+        +--------------+
|               |        |              |
| folder object +------->+ item  object |
|               |        |              |
+---------------+        +--------------+

```

## Expected behavior

after delete the `folder`

- `get_object_by_oid(folder_oid)` return `None`
- `get_object_by_oid(item_oid)` return `None`

## Actual behavior

after delete `folder`

- `get_object_by_oid(folder_oid)` return `None`, it's fine.
- `get_object_by_oid(item_oid)` return the `item` object with None `__parent__`.

## steps reproduce

just create folder and child item, then delete the folder, item still could access by `get_object_by_oid`.

1. `guillotina create --template application`
2. add a service in `api.py` 
```python
@configure.service(method='GET', name='@any/{oid}', context=IContainer)
async def get_any_by_oid(context, requeset):
    oid = requeset.matchdict['oid']
    obj = await get_object_by_oid(oid)
    return {'obj': obj.id if obj else None}
```
3. create `test_api.py` in `guillotina_app/tests/`
```python
import json


async def test_get_deleted_child(csp_requester):
    async with csp_requester as requester:
        response, code = await requester('POST',
                                         '/db/guillotina/',
                                         data=json.dumps({
                                             '@type': 'Folder',
                                             'id': 'myfolder',
                                             'title': 'my folder',
                                             'description': ''
                                         }))
        assert code == 201

        response, code = await requester('POST',
                                         '/db/guillotina/myfolder',
                                         data=json.dumps({
                                             '@type': 'Item',
                                             'id': 'myitem',
                                             'title': 'my item',
                                             'description': ''
                                         }))
        assert code == 201

        oid = response['UID']

        response, code = await requester('DELETE', '/db/guillotina/myfolder')
        assert code == 200

        response, code = await requester('GET', f'/db/guillotina/@any/{oid}')
        assert code == 200
```

**Comment by panjunyong** [comment]
@vangheem 

Just submitted a PR including the test. 

The robot tells us to sign the Plone Contributor Agreement. Since we will contribute more later, I think we should sign it.

**Comment by bloodbare** [comment]
Thanks a lot, @nnnewb and @panjunyong for the detailed explanation.

Our concept is that in order to get an object on a traversal environment is to follow the tree to get to the object, its a performance compromise, we know. For example, moving all children to update the parent_id to None requires a huge batch process.

Why we are assuming that most of the access is done on traversal: security. If we don't load the parents the logic to understand who has access is not fully available which means that can only be used on internal logic. Its a complex performance/functionality balance. Which is your use case for get_object_by_oid?

**Comment by vangheem** [comment]
Thank you for your PR! I understand now and I'm sorry I didn't see it earlier.

Maybe we should raise a KeyError or AttributeError when we have a tombstoned object?

Another option is to tweak the queries to make sure not to select objects when `parent_id` is trashed.

**Comment by panjunyong** [comment]
uuid is the only way to reference resources since path can be changed. 

permission check is offen used as context.  but usually not necessary when referenced by the context. 

raise an KeyError seems a better way.

**Comment by vangheem** [comment]
Cool. I like doing `KeyError` then!
