### ISSUE TITLE
Proposal: API consistency for GET @search

### ISSUE THREAD

**Issue by jordic** [plone/guillotina#759]
Actually we have two stories, one for elastic and one for pgcatalog.
The implementations of `GET /container/@search` it's not done, and also, as pointed by @bloodbare it has the delay on time inconsistency, not so usable for an "admin dashboard". 

If I'm not worng, last sprint, we proposed to standarize the pgcatalog as a fallback for the elastic. Also we talk about being able to have both running, or at least forward querys to both. 

To make the API more consistent, I propose to forward the default `GET /folder/@search` to use the pgcatalog (if user has opted in on the jsonb indexing). Otherside, the `POST @search` still hits elastic if it's installed. With this, thought we have backwards compatibility (@masipcat , @vangheem), are yours using the GET @serch for something? 

What do you think? (I know it's a bit wired, but anyway I think it's better solution, than having a service that with elastic doesn't work)

**Comment by jordic** [comment]
Something like this, could do the job:
```
from guillotina import configure
from guillotina.interfaces import IResource
from guillotina.api.search import QUERY_PARAMETERS
from guillotina.contrib.catalog.pg import PGSearchUtility
from guillotina.contrib.catalog.pg import Parser
from guillotina.utils import find_container
from guillotina.exceptions import ContainerNotFound


@configure.service(
    context=IResource,
    method="GET",
    permission="guillotina.SearchContent",
    name="@search",
    validate=True,
    parameters=QUERY_PARAMETERS,
    summary="Make search request",
    responses={
        "200": {
            "description": "Search results",
            "content": {
                "application/json": {
                    "schema": {"type": "object", "$ref": "#/components/schemas/SearchResults"}
                }
            },
        }
    },
)
async def search_get(context, request):
    q = dict(request.url.query)
    tool = PGSearchUtility()
    parser_tool = Parser(tool, context)
    parsed_query = parser_tool(q)
    container = find_container(context)
    if container is not None:
        return await tool.search(container, parsed_query)
    raise ContainerNotFound()
```
Anyway, things we discussed with @masipcat:
1. Rename the endpoint, to something like @pgsearch
2. Restrict it to users on postgresql
3. If I'm not wrong indexes are not created by default (They are created on tool initialitzation)...

**Comment by jordic** [comment]
After initializing indexes, with our dataset (around 46K objects), querys are slow ... (between 600-700ms)...

**Comment by vangheem** [comment]
Is there a way to see what indexes are used in that query? Maybe indexes are not quite right?

Might also be that pg is just not fast for full text queries.

As to your original question, I thought the ES implementation was done. What is wrong with it?

I guess I'm not sure about mixing/matching both catalogs--it's not really designed to work that way I guess(maybe it should?).

I would probably prefer `@pgsearch` approach so it's less magical... Or I guess only use elasticsearch for full text searches since those are so bad in pg.

I don't use the `@search` endpoints and am fine changing the implementation!

We have a sync meeting the 17th and can try to discuss this more in depth then as well.
